package org.twinecoin.test;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.List;

import org.twinecoin.test.crypt.BouncyCastleLoader;
import org.twinecoin.test.vectors.HashTestVectors;
import org.twinecoin.test.vectors.U512TestVectors;

public class TwineTest implements Runnable {

	public final static String[] MIT_HEADER = new String[] {
		"/**          Copyright (c) 2017-2019 Twinecoin Developers\n" +
		" * The file is licenced under the MIT software license, see LICENCE\n" +
		" * or http://www.opensource.org/licenses/mit-license.php.\n" +
		" */"
	};

	public static void main(String[] args) {
		if (!BouncyCastleLoader.init(TwineTest.class.getCanonicalName())) {
			System.err.println("Initialization Failure for Bouncy Castle Provider");
			return;
		}
	}

	@Override
	public void run() {
		writeFile("vectors_u512.h", U512TestVectors.generateVectors());
		writeFile("vectors_hash.h", HashTestVectors.generateVectors());
	}

	private static void writeFile(String filename, List<String> lines) {
		File dir = new File("out");

		dir.mkdirs();

		File file = new File(dir, filename);

		FileOutputStream fos = null;
		try {
			fos = new FileOutputStream(file);

			BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(fos, StandardCharsets.UTF_8));

			for (String line : MIT_HEADER) {
				writer.write(line);
				writer.newLine();
			}

			String defineName = filename.toUpperCase().replace('.', '_');
			writer.write("#ifndef " + defineName);
			writer.newLine();

			writer.write("#define " + defineName);
			writer.newLine();

			writer.newLine();

			writer.write("/*");
			writer.newLine();

			writer.write(" *        TwineTest Java Test Vector Generator");
			writer.newLine();

			writer.write(" *");
			writer.newLine();

			writer.write(" *         AUTO-GENERATED FILE - DO NOT EDIT");
			writer.newLine();

			writer.write(" *");
			writer.newLine();

			writer.write(" * This file was generated by TwineTest.  All edits should be submitted to");
			writer.newLine();

			writer.write(" * the project at https://github.com/twinecoin/twinetest");
			writer.newLine();

			writer.write(" */");
			writer.newLine();

			for (String line : lines) {
				writer.write(line);
				writer.newLine();
			}

			writer.newLine();
			writer.write("#endif");
			writer.newLine();

			writer.close();
		} catch (IOException e) {
			System.out.println("Unable to output file for writing, " + file);
		} finally {
			if (fos != null) {
				try {
					fos.close();
				} catch (IOException e) {}
			}
		}
	}
}
