package org.twinecoin.test;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.List;

import org.twinecoin.test.crypt.BouncyCastleLoader;
import org.twinecoin.test.vectors.SHA256TestVectors;
import org.twinecoin.test.vectors.U256TestVectors;

public class TwineTest {
	
	public final static String[] MIT_HEADER = new String[] {
		"/**              Copyright (c) 2017 Twinecoin Developers",
		" * The file is licenced under the MIT software license, see LICENCE",
		" * or http://www.opensource.org/licenses/mit-license.php.",
		" */"
	};

	public static void main(String[] args) {
		if (!BouncyCastleLoader.init()) {
			System.out.println("Initialization Failure for Bouncy Castle Provider");
			return;
		}

		writeFile("vectors_u256.h", U256TestVectors.generateVectors());
		writeFile("vectors_sha256.h", SHA256TestVectors.generateVectors());
	}
	
	private static void writeFile(String filename, List<String> lines) {
		File dir = new File("out");
		
		dir.mkdirs();
		
		File file = new File(dir, filename);
		
		FileOutputStream fos = null;
		try {
			fos = new FileOutputStream(file);
			
			BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(fos, StandardCharsets.UTF_8));
			
			for (String line : MIT_HEADER) {
				writer.write(line);
				writer.newLine();
			}

			String defineName = filename.toUpperCase().replace('.', '_');
			writer.write("#ifndef " + defineName);
			writer.newLine();
			
			writer.write("#define " + defineName);
			writer.newLine();
			
			writer.newLine();
			
			writer.write("/*");
			writer.newLine();
			
			writer.write(" *        TwineTest Java Test Vector Generator");
			writer.newLine();
			
			writer.write(" *");
			writer.newLine();
			
			writer.write(" *         AUTO-GENERATED FILE - DO NOT EDIT");
			writer.newLine();
			
			writer.write(" *");
			writer.newLine();
			
			writer.write(" * This file was generated by TwineTest.  All edits should be submitted to");
			writer.newLine();
			
			writer.write(" * the project at https://github.com/twinecoin/twinetest");
			writer.newLine();
			
			writer.write(" */");
			writer.newLine();
			
			for (String line : lines) {
				writer.write(line);
				writer.newLine();
			}
			
			writer.newLine();
			writer.write("#endif");
			writer.newLine();
			
			writer.close();
		} catch (IOException e) {
			System.out.println("Unable to output file for writing, " + file);
		} finally {
			if (fos != null) {
				try {
					fos.close();
				} catch (IOException e) {}
			}
		}
	}

}
